### PR TITLE
Support reverse from Django 2.0

### LINKED ISSUE #8: ImportError: cannot import name 'urlresolvers'
ImportError: cannot import name 'urlresolvers' 
This error occurerd while working with django 2.0

### PR DESCRIPTION
**Pull request by dmvass**
The **django.core.urlresolvers** module is removed in favor of its new location, **django.urls**.

Closes #8

### CODE REVIEW

**Comment by dmvass** [comment]
@gavinwahl friendly ping. Could you review this PR?

**Comment by dmvass** [comment]
@gavinwahl could you reviewing my PR?

**Comment by mverteuil** [comment]
@gavinwahl @fusionbox

Also pinging on this, the branch works well for us too.

File: .gitignore [hunk 1]
```diff
@@ -8,3 +8,4 @@ pep8.txt
 dist/
 build/
 .tox
+venv/
```
Comment (gavinwahl) [inline .gitignore:11]: Why?

**Review by gavinwahl — COMMENTED** [review]
Why is this necessary? Doesn't tox support multiple python versions?

**Comment by dmvass** [comment]
@gavinwahl tox was not working with travis ci please see https://travis-ci.org/fusionbox/django-absoluteuri/builds/340116977?utm_source=github_status&utm_medium=notification

File: .gitignore (hunk 1 above)
Comment (dmvass) [reply .gitignore:11]: I didn't find any environment directory name and added `venv`.

**Comment by dmvass** [comment]
@gavinwahl do you have a time for review this PR and bump version? kind regards!

**Comment by hugoseabra** [comment]
I believe it is time to approve this. What do you think? Let's update python and django versions?

**Comment by gavinwahl** [comment]
fixed in fc377cad82a
