### ISSUE TITLE
ImportError: cannot import name 'urlresolvers'

### ISSUE THREAD

**Issue by rossi1** [fusionbox/django-absoluteuri#8]
ImportError: cannot import name 'urlresolvers' 
This error occurerd while working with django 2.0

**Comment by dmvass** [comment]
fixed in #7
